#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tree_root="$(cd "${script_dir}/.." && pwd)"
twrp_source="${TWRP_SOURCE:-$(pwd)}"

if [[ ! -f "${twrp_source}/build/envsetup.sh" ]]; then
    echo "TWRP source not found at: ${twrp_source}" >&2
    echo "Run from the TWRP source root or set TWRP_SOURCE." >&2
    exit 1
fi

twrp_source="$(cd "${twrp_source}" && pwd)"
target_tree="${twrp_source}/device/xiaomi/marble"

if [[ "${tree_root}" != "${target_tree}" ]]; then
    command -v rsync >/dev/null || {
        echo "rsync is required to copy the device tree." >&2
        exit 1
    }
    mkdir -p "${target_tree}"
    rsync -a --delete \
        --exclude=.git \
        --exclude=.github \
        --exclude=.codex-cache \
        --exclude=.codex-context \
        "${tree_root}/" "${target_tree}/"
fi

cd "${twrp_source}"
export ALLOW_MISSING_DEPENDENCIES=true
# Generated by the selected Android source tree and intentionally external to
# this device-tree repository.
# shellcheck disable=SC1091
source build/envsetup.sh
lunch twrp_marble-bp2a-eng
m "${BUILD_JOBS:--j$(nproc)}" recoveryimage

image="${OUT_DIR:-${twrp_source}/out}/target/product/marble/recovery.img"
[[ -s "${image}" ]] || {
    echo "Build completed without a recovery image: ${image}" >&2
    exit 1
}

echo "Built: ${image}"
sha256sum "${image}"
