#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tree_root="$(cd "${script_dir}/.." && pwd)"
twrp_source="${TWRP_SOURCE:-$(pwd)}"
twrp_product="${TWRP_PRODUCT:-twrp_marble}"

case "${twrp_product}" in
    twrp_marble|twrp_marble_wifi)
        ;;
    *)
        echo "Unsupported TWRP product: ${twrp_product}" >&2
        exit 1
        ;;
esac

if [[ ! -f "${twrp_source}/build/envsetup.sh" ]]; then
    echo "TWRP source not found at: ${twrp_source}" >&2
    echo "Run from the TWRP source root or set TWRP_SOURCE." >&2
    exit 1
fi

twrp_source="$(cd "${twrp_source}" && pwd)"
target_tree="${twrp_source}/device/xiaomi/marble"

if [[ "${tree_root}" != "${target_tree}" ]]; then
    command -v rsync >/dev/null || {
        echo "rsync is required to copy the device tree." >&2
        exit 1
    }
    mkdir -p "${target_tree}"
    rsync -a --delete \
        --exclude=.git \
        --exclude=.github \
        --exclude=.codex-cache \
        --exclude=.codex-context \
        "${tree_root}/" "${target_tree}/"
fi

if [[ "${twrp_product}" == "twrp_marble_wifi" ]]; then
    bash "${target_tree}/scripts/prepare-wifi-source.sh" "${twrp_source}"
    if [[ -z "${OUT_DIR:-}" ]]; then
        export OUT_DIR="out-marble-wifi"
    fi
fi

bash "${target_tree}/scripts/apply-patches.sh" "${twrp_source}" "${twrp_product}"

cd "${twrp_source}"

# Removed prebuilts and relinked libraries can survive in an incremental out
# directory even after their source files change. Purge only the obsolete
# vibrator stack and the recovery packaging stamps so the ramdisk is rebuilt
# from the current device tree and patched TWRP libraries.
product_out="${OUT_DIR:-out}/target/product/marble"
for stale_file in \
    recovery/root/system/bin/vendor.qti.hardware.vibrator.service \
    recovery/root/system/etc/init/vendor.qti.hardware.vibrator.service.rc \
    recovery/root/vendor/etc/vintf/manifest/vendor.qti.hardware.vibrator.service.xml \
    recovery/root/vendor/lib64/libaachaptics.so \
    recovery/root/vendor/lib64/libqtivibratoreffect.xiaomi.so \
    recovery/root/vendor/lib64/libqtivibratoreffectoffload.so \
    recovery/root/vendor/lib64/vendor.qti.hardware.vibrator.impl.so \
    recovery/root/vendor/lib64/vendor.qti.hardware.vibratorOL.impl.so \
    recovery/root/vendor/lib64/vendor.qti.hardware.vibratorSel.impl.so; do
    rm -f -- "${product_out}/${stale_file}"
done
rm -f -- \
    "${product_out}/obj/FAKE/relink_libraries_intermediates/relink_libraries-timestamp" \
    "${product_out}/recovery/root/relink_libraries-timestamp" \
    "${product_out}/obj/PACKAGING/recovery_intermediates/ramdisk_files-timestamp" \
    "${product_out}/ramdisk-recovery.img" \
    "${product_out}/recovery.img"

export ALLOW_MISSING_DEPENDENCIES=true
# Generated by the selected Android source tree and intentionally external to
# this device-tree repository.
# shellcheck disable=SC1091
set +u
source build/envsetup.sh
lunch "${twrp_product}-bp2a-eng"
m "${BUILD_JOBS:--j$(nproc)}" recoveryimage
set -u

image="${OUT_DIR:-${twrp_source}/out}/target/product/marble/recovery.img"
[[ -s "${image}" ]] || {
    echo "Build completed without a recovery image: ${image}" >&2
    exit 1
}

echo "Built: ${image}"
sha256sum "${image}"
